### ISSUE TITLE
help command doesn't work

### ISSUE THREAD

**Issue by IYR3775** [kk5dire/pp-bot#1]
-tried restoring unmodified help.js

**Comment by kk5dire** [comment]
@IYR3775 is going to try reproducing the error in the main source code
@kk5dire is going to try a stop error check

**Comment by kk5dire** [comment]
It looks as if my editor is thinking their is a syntax error in lines 1-27 help.js 
1-4 first logged error
`kk5dire@penguin:~/pp-bot$ const Command = require("../../base/Command.js"),
bash: syntax error near unexpected token `('
kk5dire@penguin:~/pp-bot$ Discord = require("discord.js"),
bash: syntax error near unexpected token `('
kk5dire@penguin:~/pp-bot$ ms = require("ms");
bash: syntax error near unexpected token `('
kk5dire@penguin:~/pp-bot$ 
`
10-27 second error logged
`bash: botPermissions:: command not found
kk5dire@penguin:~/pp-bot$             nsfw: false,
bash: nsfw:: command not found
kk5dire@penguin:~/pp-bot$             ownerOnly: false,
bash: ownerOnly:: command not found
kk5dire@penguin:~/pp-bot$             cooldown: 5000
bash: cooldown:: command not found
kk5dire@penguin:~/pp-bot$         });
bash: syntax error near unexpected token `}'
kk5dire@penguin:~/pp-bot$     }
bash: syntax error near unexpected token `}'
kk5dire@penguin:~/pp-bot$ `

**Comment by kk5dire** [comment]
this rep has now been moved to https://github.com/IYR3775/pp-bot
